### ISSUE TITLE
Enable code coverage diffs

### ISSUE THREAD

**Issue by rnc** [project-ncl/bacon#320]
Note that @dwalluck  added `.codecov.yml` to PME:
```
coverage:
  status:
    project:
      default:
        threshold: 1%
    patch:
      default:
        threshold: 1%
```
